language: c
dist: bionic
sudo: required

matrix:
  include:
    - os: linux
      env: DISTRIBUTED=False
#   - os: linux
#     env: DISTRIBUTED=True

script:
- "./.travis/build.sh"

after_success:
- "./.travis/documentation.sh"
- "./.travis/deploy.sh"

deploy:
  - provider: releases
    api_key:
      secure: Fa17BBA9wgJZPQd4ED0hao4dop0yDHimbmDaGJEAL/PD6m5VDU+NmyWRUcp+mctGBkiTex8k3BPDsJg4hF/0O1RGW2AXut4LyWoA+U8Big6o+clZHCOkEP3sSlSV+MYuu9eTCKj3RdZTfD/dDSBKJU2IRfqTG/1/HbBswRFMclOaj7sBtxAKBzRVE7jRcuNnl9wi55LB5PWqn/lWGkIEko1LCmx48HgddHMM/v/ekB2MHhRyeJBHzkYnfUCLG38L1zxQN1NZcNRsJFQ8EmZYVsOvFfsC8Pl6/DG6EIdizxWCpLdh4JhTAyPwmLafWO3lHH+2HyKW6K2fVP4XpNvm5C5hCtYdObgLjAL2SYvF78MFmdmA0g13U5s8muqbrOE1zztApJ/XGkStecORQtp/95P34AIMXIs8M7fN0f3UVmx4Cchv5LFWgM7cGlOjCLV33+gxAIDnWpV8u6k134fkn9ipFurrx5EV5LoEU2AtFSoCPzgInbBjYJ88Ff/A3SO3vTLE7kJ8FRvalGB59nmmAMQWx/sl7KQWxgssJ3RaE/R3yajNJFXMCJ3W5FXIoG0mYAVKOYSTK9/zYw4VtMDrHjJQzoJgA5goZaLdjKEQYG4kdpRegMF5jOKN39k/7HwJTFDSJWtSloxRivkjkLBP3NYY6l8ned066zqzG4Eu81I=
    file: 'bin/imitator-$TRAVIS_TAG-amd64'
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux && $DISTRIBUTED = False
  - provider: releases
    api_key:
      secure: Fa17BBA9wgJZPQd4ED0hao4dop0yDHimbmDaGJEAL/PD6m5VDU+NmyWRUcp+mctGBkiTex8k3BPDsJg4hF/0O1RGW2AXut4LyWoA+U8Big6o+clZHCOkEP3sSlSV+MYuu9eTCKj3RdZTfD/dDSBKJU2IRfqTG/1/HbBswRFMclOaj7sBtxAKBzRVE7jRcuNnl9wi55LB5PWqn/lWGkIEko1LCmx48HgddHMM/v/ekB2MHhRyeJBHzkYnfUCLG38L1zxQN1NZcNRsJFQ8EmZYVsOvFfsC8Pl6/DG6EIdizxWCpLdh4JhTAyPwmLafWO3lHH+2HyKW6K2fVP4XpNvm5C5hCtYdObgLjAL2SYvF78MFmdmA0g13U5s8muqbrOE1zztApJ/XGkStecORQtp/95P34AIMXIs8M7fN0f3UVmx4Cchv5LFWgM7cGlOjCLV33+gxAIDnWpV8u6k134fkn9ipFurrx5EV5LoEU2AtFSoCPzgInbBjYJ88Ff/A3SO3vTLE7kJ8FRvalGB59nmmAMQWx/sl7KQWxgssJ3RaE/R3yajNJFXMCJ3W5FXIoG0mYAVKOYSTK9/zYw4VtMDrHjJQzoJgA5goZaLdjKEQYG4kdpRegMF5jOKN39k/7HwJTFDSJWtSloxRivkjkLBP3NYY6l8ned066zqzG4Eu81I=
    file: 'bin/patator-$TRAVIS_TAG-amd64'
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux && $DISTRIBUTED = True
  - provider: releases
    api_key:
      secure: Fa17BBA9wgJZPQd4ED0hao4dop0yDHimbmDaGJEAL/PD6m5VDU+NmyWRUcp+mctGBkiTex8k3BPDsJg4hF/0O1RGW2AXut4LyWoA+U8Big6o+clZHCOkEP3sSlSV+MYuu9eTCKj3RdZTfD/dDSBKJU2IRfqTG/1/HbBswRFMclOaj7sBtxAKBzRVE7jRcuNnl9wi55LB5PWqn/lWGkIEko1LCmx48HgddHMM/v/ekB2MHhRyeJBHzkYnfUCLG38L1zxQN1NZcNRsJFQ8EmZYVsOvFfsC8Pl6/DG6EIdizxWCpLdh4JhTAyPwmLafWO3lHH+2HyKW6K2fVP4XpNvm5C5hCtYdObgLjAL2SYvF78MFmdmA0g13U5s8muqbrOE1zztApJ/XGkStecORQtp/95P34AIMXIs8M7fN0f3UVmx4Cchv5LFWgM7cGlOjCLV33+gxAIDnWpV8u6k134fkn9ipFurrx5EV5LoEU2AtFSoCPzgInbBjYJ88Ff/A3SO3vTLE7kJ8FRvalGB59nmmAMQWx/sl7KQWxgssJ3RaE/R3yajNJFXMCJ3W5FXIoG0mYAVKOYSTK9/zYw4VtMDrHjJQzoJgA5goZaLdjKEQYG4kdpRegMF5jOKN39k/7HwJTFDSJWtSloxRivkjkLBP3NYY6l8ned066zqzG4Eu81I=
    file: 'doc/IMITATOR-user-manual.pdf'
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
  - provider: releases
    api_key:
      secure: Fa17BBA9wgJZPQd4ED0hao4dop0yDHimbmDaGJEAL/PD6m5VDU+NmyWRUcp+mctGBkiTex8k3BPDsJg4hF/0O1RGW2AXut4LyWoA+U8Big6o+clZHCOkEP3sSlSV+MYuu9eTCKj3RdZTfD/dDSBKJU2IRfqTG/1/HbBswRFMclOaj7sBtxAKBzRVE7jRcuNnl9wi55LB5PWqn/lWGkIEko1LCmx48HgddHMM/v/ekB2MHhRyeJBHzkYnfUCLG38L1zxQN1NZcNRsJFQ8EmZYVsOvFfsC8Pl6/DG6EIdizxWCpLdh4JhTAyPwmLafWO3lHH+2HyKW6K2fVP4XpNvm5C5hCtYdObgLjAL2SYvF78MFmdmA0g13U5s8muqbrOE1zztApJ/XGkStecORQtp/95P34AIMXIs8M7fN0f3UVmx4Cchv5LFWgM7cGlOjCLV33+gxAIDnWpV8u6k134fkn9ipFurrx5EV5LoEU2AtFSoCPzgInbBjYJ88Ff/A3SO3vTLE7kJ8FRvalGB59nmmAMQWx/sl7KQWxgssJ3RaE/R3yajNJFXMCJ3W5FXIoG0mYAVKOYSTK9/zYw4VtMDrHjJQzoJgA5goZaLdjKEQYG4kdpRegMF5jOKN39k/7HwJTFDSJWtSloxRivkjkLBP3NYY6l8ned066zqzG4Eu81I=
    file: 'doc/IMITATOR-not-developer-manual.pdf'
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
