name: workflow

on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    env:
      DISTRIBUTED: False
    steps:
      # setup repository
      - name: Checkout
        uses: actions/checkout@v2

      # install dependencies
      - name: Run build
        run: .github/scripts/build.sh
        shell: bash

      # build documentation
      - name: Documentation
        run: .github/scripts/documentation.sh
        shell: bash

      # upload artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            bin/*
            doc/IMITATOR-user-manual.pdf
            doc/IMITATOR-not-developer-manual.pdf

  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build
    steps:
      # checkout project
      - name: Checkout
        uses: actions/checkout@v2

      # retrieve information
      - name: Retrieve artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifacts

      # get tag name
      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      # prepare deploy
      - name: Prepare deploy
        run: .github/scripts/deploy.sh
        shell: bash

      # deploy
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG }}
          release_name: ${{ env.TAG }}
          files: |
            bin/*
            doc/IMITATOR-user-manual.pdf
            doc/IMITATOR-not-developer-manual.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
